### DISCUSSION TITLE
REST API Activity Sensor For Home Assistant

### DISCUSSION THREAD

**Discussion by AlexKusnezov** [CyferShepard/Jellystat#399] [Q&A]
Guys, I've been playing this around a little bit and what I want is to have a sensor in HA that displays all of the data for the current stream, e.g. audio format and number of channels, similar to this integration: https://github.com/Richardvaio/Tautulli_Active_Streams

So far I've benn able to retrive the user, play state, method, anme and path:
```
- platform: rest
  unique_id: jellystat
  name: Jellystat
  icon: mdi:jellyfish
  resource: http://192.168.2.10:3000/proxy/getSessions
  headers:
    X-API-Token: my-api-token
    Content-Type: application/json
  value_template: "{{value_json[0].UserName| default}},{{value_json[0].PlayState.PlayMethod | default}}"
  json_attributes_path: "$.[0].NowPlayingItem"
  json_attributes:
    - Name
    - Path
```

However I'm still missing datae that is especially relevant for me, which is audio codec and number of audio channels.
The purpose for this is, that I have a surround system that I can control throguh HA and based on jellystat data I want to automate thing, e.g. apply correct surropund volume.

I'm already doing this for plex with the above mentioned tautulli integration, but I would love to have it for jellyfin also, since plex will probably stop at some time being a free version for local playback.
