### ISSUE TITLE
Allow specifying UID/GID in docker container

### ISSUE THREAD

**Issue by broizter** [CyferShepard/Jellystat#148]
For security purposes it would be great if it was possible to specify what user id and group id when running the docker container. See linuxserver.io for an example. https://docs.linuxserver.io/general/understanding-puid-and-pgid/

**Comment by DuvelCorp** [comment]
Nothing prevents you to do it.
I just installed Jellystats and run it with my Jellyfin user and its fine.

I do had the errors with NPM linked above. The solution was rather simple: just mount the internal container folder /.npm as an external volume and give it the correct permissions. This has another advantage, you have a direct access to the npm logs on your host.

Say you want UID 115 and GID 121
You end up with the following

On the host server:
```
sudo mkdir /opt/jellystat
sudo mkdir /opt/jellystat/db
sudo mkdir /opt/jellystat/backup_db
sudo mkdir /opt/jellystat/npm
sudo chown -R 115:121 /opt/jellystat
```

In docker:
```
version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    container_name: jellystat_db
    user: 115:121 # your host UID:GID
    environment:
      TZ: "Europe/Brussels"
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxxxxxx
    volumes:
    - /opt/jellystat/db:/var/lib/postgresql/data 
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    user: 115:121 # your host UID:GID
    environment:
      TZ: "Europe/Brussels"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxxxxxx
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'xxxxxxxxx'
    ports:
      - "3000:3000" #Server Port
    volumes:
      - /opt/jellystat/backup_db:/app/backend/backup-data 
      - /opt/jellystat/npm:/.npm
    depends_on:
      - jellystat-db
    restart: unless-stopped
```
