### ISSUE TITLE
JS_BASE_URL not working in docker

### ISSUE THREAD

**Issue by flosoft** [CyferShepard/Jellystat#229]
**Describe the bug**
The JS_BASE_URL is not working when configured in the environment of the docker container.

The webpage continues to try to load with the base URL of /
```
services:
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      <snip/>
      JS_BASE_URL: "/jellystat/"
      <snip/>

```

**Environment Details (please complete the following information):**
- Docker
 - Jellystat Version: 1.1.0

**To Reproduce**
Deploy docker container with `JS_BASE_URL` set.
Open webpage.

**Expected behavior**
The page should be loading with the `JS_BASE_URL` prefix instead of `/`
