### ISSUE TITLE
"Unable to connect to Jellyfin Server" with a Tailscale setup

### ISSUE THREAD

**Issue by lluni** [CyferShepard/Jellystat#24]
I have a rather complicated setup involving Tailscale (which allows remote hosts, which aren't public, to be treated as if they're in the same local network), but that shouldn't matter, because the Tailscale IPs work from within other Docker containers.

I have Jellyfin installed on a local Raspberry Pi 4 and Jellystat on a remote VPS (reachable via `https://jellystat.example.com`), because of #23. From the VPS perspective, Jellyfin is reachable via `http://100.64.0.2:8096` (I've already tested this with a nginx container, which can reverse proxy that IP successfully). For the record, this IP is only accessible by the VPS and not by my browser, because my browser isn't in that Tailscale network but the VPS is.

Now, If I set the server URL inside Jellystat to `http://100.64.0.2:8096`, it displays "Unable to connect to Jellyfin Server" as if the browser and not the container would try to access that URL. 
If I reverse proxy `http://100.64.0.2:8096` via nginx(proxymanager) to be accessible at `https://jellyfin.example.com` and set this URL to be the server URL inside Jellystat, it suddenly works, but I would like to avoid making the the Jellyfin server publicly accessible. I assume this is the case, because the browser can access `https://jellyfin.example.com` but not the IP, but that would suggest that the browser and not the Jellystat container is the one trying to connect to the set server URL, which seems rather weird.
I inspected the browser network tab after setting the server URL to the Jellyfin domain, which showed a lot of connections to the set domain. This seems like the browser/frontend does all the connections, even though the backend/container should do that.

Also, I can't seem to be able to access websockets, maybe that could also be a reason? When I access the Jellystat webinterface, the browser console logs that it can't connect to `wss://jellystat.domain.com:3000/ws`, even though it should be `wss://jellystat.domain.com/ws`, because the reverse proxy setup already gets rid of needing to use ports.

My `docker-compose.yml` for reference:
```YAML
services:
  jellystat-db:
    image: postgres
    container_name: jellystat-db
    environment:
      POSTGRES_USER: [redacted]
      POSTGRES_PASSWORD: [redacted]
    networks:
      - jellystat
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    environment:
      POSTGRES_USER: [redacted]
      POSTGRES_PASSWORD: [redacted]
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: [redacted]
    #ports:
      #- "3000:3000" #Server Port
      #- "3004:3004" #websocket port
    networks:
      - jellystat
      - npm_bridge
    volumes:
      - ./data:/backup-data # Mounting the volume
    depends_on:
      - jellystat-db

networks:
  jellystat:
  npm_bridge:
    external: true
```
