### ISSUE TITLE
Docker Compose :  (root) additional property logging is not allowed

### ISSUE THREAD

**Issue by nodecentral** [CyferShepard/Jellystat#247]
Hi

Sorry not sure what to provide, as I’m right at the very start trying to get Docker to accept my compose file (via QNAP Container Stations) ?  But it returns an exit status 15: (root) additional property logging is not allowed.

<img width="435" alt="image" src="https://github.com/user-attachments/assets/532152d8-f0b7-41e6-b675-f98f6d53c3d4">

I took the compose directly from your main repo page, and only changed the bind locations, I have admin privileges on the box and I also validated the YAML was formatted correctly ?
 
Have you encountered this before ?   - Here is my compose file.

````
version: '3'

services:
  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /share/Container/jellystat/postgres-data:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: "my-secret-jwt-key"
      TZ: Europe/London # timezone (ex: Europe/Paris)
    volumes:
      - /share/Container/jellystat/jellystat-backup-data:/app/backend/backup-data
    ports:
      - "8097:3000"
    depends_on:
      - jellystat-db
      
networks:
  default:

volumes:
  postgres-data:
  jellystat-backup-data:

logging:
  driver: "json-file"
  options:
    max-file: "5" # number of files or file count
    max-size: "10m" # file size
````
