### ISSUE TITLE
errors in jellystat-db and jellystat-app containers

### ISSUE THREAD

**Issue by Hydranet** [CyferShepard/Jellystat#35]
I checked my app and db container and found the following errors.

jellystat-app:
```
1] webpack compiled successfully
[0] Unexpected error on idle client error: terminating connection due to administrator command
[0]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
[0]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
[0]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
[0]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
[0]     at Socket.emit (node:events:511:28)
[0]     at addChunk (node:internal/streams/readable:332:12)
[0]     at readableAddChunk (node:internal/streams/readable:305:9)
[0]     at Readable.push (node:internal/streams/readable:242:10)
[0]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
[0]   length: 116,
[0]   severity: 'FATAL',
[0]   code: '57P01',
[0]   detail: undefined,
[0]   hint: undefined,
[0]   position: undefined,
[0]   internalPosition: undefined,
[0]   internalQuery: undefined,
[0]   where: undefined,
[0]   schema: undefined,
[0]   table: undefined,
[0]   column: undefined,
[0]   dataType: undefined,
[0]   constraint: undefined,
[0]   file: 'postgres.c',
[0]   line: '3218',
[0]   routine: 'ProcessInterrupts',
[0]   client: Client {
[0]     _events: [Object: null prototype] { error: [Function (anonymous)] },
[0]     _eventsCount: 1,
[0]     _maxListeners: undefined,
[0]     connectionParameters: ConnectionParameters {
[0]       user: 'jellystat',
[0]       database: 'jfstat',
[0]       port: 5432,
[0]       host: 'jellystat-db',
[0]       binary: false,
[0]       options: undefined,
[0]       ssl: false,
[0]       client_encoding: '',
[0]       replication: undefined,
[0]       isDomainSocket: false,
[0]       application_name: undefined,
[0]       fallback_application_name: undefined,
[0]       statement_timeout: false,
[0]       lock_timeout: false,
[0]       idle_in_transaction_session_timeout: false,
[0]       query_timeout: false,
[0]       connect_timeout: 0
[0]     },
[0]     user: 'jellystat',
[0]     database: 'jfstat',
[0]     port: 5432,
[0]     host: 'jellystat-db',
[0]     replication: undefined,
[0]     _Promise: [Function: Promise],
[0]     _types: TypeOverrides { _types: [Object], text: {}, binary: {} },
[0]     _ending: true,
[0]     _connecting: false,
[0]     _connected: true,
[0]     _connectionError: false,
[0]     _queryable: false,
[0]     connection: Connection {
[0]       _events: [Object: null prototype],
[0]       _eventsCount: 23,
[0]       _maxListeners: undefined,
[0]       stream: [Socket],
[0]       _keepAlive: false,
[0]       _keepAliveInitialDelayMillis: 0,
[0]       lastBuffer: false,
[0]       parsedStatements: {},
[0]       ssl: false,
[0]       _ending: false,
[0]       _emitMessage: false,
[0]       _connecting: true,
[0]       [Symbol(kCapture)]: false
[0]     },
[0]     queryQueue: [],
[0]     binary: false,
[0]     processID: 31,
[0]     secretKey: -1913963847,
[0]     ssl: false,
[0]     _connectionTimeoutMillis: 0,
[0]     _connectionCallback: null,
[0]     saslSession: null,
[0]     serverVersion: '15.3 (Debian 15.3-1.pgdg110+1)',
[0]     release: [Function (anonymous)],
[0]     activeQuery: null,
[0]     readyForQuery: true,
[0]     hasExecuted: true,
[0]     _poolUseCount: 393,
[0]     [Symbol(kCapture)]: false
[0]   }
[0] }
npm ERR! path /app
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c concurrently "npm run start-server" "npm start"

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-05-30T11_36_13_530Z-debug-0.log
```
jellystat-db:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-05-30 11:36:12.440 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-05-30 11:36:12.441 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-05-30 11:36:12.441 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-05-30 11:36:12.444 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-05-30 11:36:12.449 UTC [24] LOG:  database system was shut down at 2023-05-30 11:35:13 UTC
2023-05-30 11:36:12.454 UTC [1] LOG:  database system is ready to accept connections
2023-05-30 11:36:14.035 UTC [28] ERROR:  database "jfstat" already exists
2023-05-30 11:36:14.035 UTC [28] STATEMENT:  CREATE DATABASE jfstat
2023-05-30 11:38:39.352 UTC [1] LOG:  received fast shutdown request
2023-05-30 11:38:39.354 UTC [1] LOG:  aborting any active transactions
2023-05-30 11:38:39.354 UTC [31] FATAL:  terminating connection due to administrator command
2023-05-30 11:38:39.354 UTC [29] FATAL:  terminating connection due to administrator command
2023-05-30 11:38:39.355 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1
2023-05-30 11:38:39.355 UTC [22] LOG:  shutting down
2023-05-30 11:38:39.358 UTC [22] LOG:  checkpoint starting: shutdown immediate
2023-05-30 11:38:39.373 UTC [22] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.008 s, total=0.018 s; sync files=3, longest=0.007 s, average=0.003 s; distance=1 kB, estimate=1 kB
2023-05-30 11:38:39.376 UTC [1] LOG:  database system is shut down
```

The strange thing is the database/backend seems to be up because the webinterface/frontend works.  I made a few changes to the example docker-compose file but even if I remove those change I still get these errors, I don't remember getting these errors before I did my last pull about the previous issue I reported.  I was wondering why I am seeing database errors even if the database is up?

**Comment by Hydranet** [comment]
```
$ cat jellystat.yml
services:
  jellystat-db:
    labels:
      - "io.containers.autoupdate=registry"
      - "PODMAN_SYSTEMD_UNIT=podman-compose@jellystat-db.service"
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: 'password'
      TZ: Europe/Amsterdam
    volumes:
      - $HOME/data/jellystat/jellystat-db/postgres-data:/var/lib/postgresql/data
  jellystat-app:
    labels:
     - "io.containers.autoupdate=registry"
     - "PODMAN_SYSTEMD_UNIT=podman-compose@jellystat-app.service"
    image: docker.io/cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: 'password'
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'secret'
      TZ: Europe/Amsterdam
    ports:
      - "3000:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - $HOME/data/jellystat/jellystat-app/backup-data:/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
networks:
  default:

```
When I use  your original docker-compose file I get the same, which looks like this.
```
services:
  jellystat-db:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: 'password'
    volumes:
      - $HOME/data/jellystat/jellystat-db/postgres-data:/var/lib/postgresql/data
  jellystat-app:
    image: docker.io/cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: 'password'
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'secret'
    ports:
      - "3000:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - $HOME/data/jellystat/jellystat-app/backup-data:/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
networks:
  default:
  ```

**Comment by CyferShepard** [comment]
can you try this compose file, your volume mount seems incorrect. Also id recommend a fresh db

```
services:
  jellystat-db:
    labels:
      - "io.containers.autoupdate=registry"
      - "PODMAN_SYSTEMD_UNIT=podman-compose@jellystat-db.service"
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: 'password'
      TZ: Europe/Amsterdam
    volumes:
      - $HOME/data/jellystat/jellystat-db/postgres-data:/var/lib/postgresql/data
  jellystat-app:
    labels:
     - "io.containers.autoupdate=registry"
     - "PODMAN_SYSTEMD_UNIT=podman-compose@jellystat-app.service"
    image: docker.io/cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: 'password'
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'secret'
      TZ: Europe/Amsterdam
    ports:
      - "3000:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - $HOME/data/jellystat/jellystat-app/backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
networks:
  default:

```
