### ISSUE TITLE
Token mismatch

### ISSUE THREAD

**Issue by botagas** [CyferShepard/Jellystat#350]
**Describe the bug**
Jellystat fails to load any info due to token mismatch if the present token in user browser is different than expected. This causes user to not be able to load in SSO-backed environments. Could be related to #260 

In my case, I have user authentication for each service that I have. Some services are only accessible after authenticating as admin. This is done via SSO, and some of the services support that. However, if Jellystat is ran behind such a system, you cannot actually access Jellystat after logging in to your SSO provider of choice.

**Environment Details (please complete the following information):**
 - OS: [e.g. Ubuntu] YNH on Debian 12
 - Browser [e.g. chrome, Mozilla] Firefox
 - Jellystat Version [e.g. 1.0.0] 1.1.3
 - Jellyfin Version [e.g. 10.0.5] 10.10.5

**To Reproduce**
1. Use SSO to grant yourself access to Jellystat resource
2. Open Jellystat page
3. See loading circles in all of the pages since none of the data can be retrieved due to error 401

**Expected behavior**
Either work with SSO or at least handle cases where before accessing Jellystat, user has to sign in to an SSO provider before (which is why the user gets a token before accessing Jellystat, thus it failing).

**Screenshots**
none

**Task Logs**
JSON response when accessing any page:
`{"message":"Invalid token"}`

**Container Logs**
none

**Additional context**

**Comment by chiva** [comment]
Can confirm this behviour
Traefik as reverse proxy works fine, as soon as I add an authentication middleware such as Authentik, after logging in, it's all 401s

**Comment by hammamboumou** [comment]
Confirm this behavious with authentik and traefik. Disable login seem like it doesn't do anything

**Comment by Bykow** [comment]
Same issue here.

**Comment by uneos-marc** [comment]
Same issue here - running it behind Authelia and its reporting mysterious 401s

**Comment by marcherschel** [comment]
Same issue with Authelia + Traefik middleware setup on k8s

**Comment by marcherschel** [comment]
In case anyone wants some kind of hack to make it work with Traefik & an SSO like Authelia for example:

- the 401 comes because this code of Jellystat checks for an apikey and token even if auth has been disabled for jellystat if it runs behind a middleware and reverse proxy

<img width="593" height="214" alt="Image" src="https://github.com/user-attachments/assets/43b88144-5e66-484b-b7ca-0ed6ceef1907" />

Since we handle auth over an external tool like Authelia we can assume that auth middleware <-> jellystat is always trusted and only authorized and authenticated users will access that.

The hack to now make it work is to create a dummy API key in the Jellystat UI:

<img width="1465" height="372" alt="Image" src="https://github.com/user-attachments/assets/a56abbf6-88d8-4f10-a4fc-eda0a4d01d01" />

and then inject that in the Traefik <-> Jellystat communication path i.e. on k8s using Authelia as auth middleware:

```yaml
...
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellystat-api-token
spec:
  headers:
    customRequestHeaders:
      x-api-token: "your api key from jellystat"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellystat
spec:
  hostnames:
  - "jellystat.example.com"
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: traefik-gateway
    namespace: ingress
    sectionName: websecure
  rules:
  - backendRefs:
    - name: jellystat
      port: 80
    filters:
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: forwardauth-authelia
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: jellystat-api-token
    matches:
    - path:
        type: PathPrefix
        value: /
```

Then it works like a charm behind the Authelia SSO with Traefik. This is not the fix but a mitigation until this is fixed in the code of Jellystat.
