### ISSUE TITLE
Error during the first setup

### ISSUE THREAD

**Issue by D3rJust1n** [CyferShepard/Jellystat#400]
I have just rolled out jellystat via Docker Compose
but during the first setup I get an error when I want to enter my Jellyfin server
Error, screenshots and my compose below

### Error
```
> jfstat@1.1.6 start
> cd backend && node server.js
env.js file has been saved successfully.
[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://0.0.0.0:3000
Task Manager Singleton created
Task Scheduler Singleton created
http://192.168.178.225:8096 true
http://192.168.178.225:8096 true
http://192.168.178.225:8096 true
[JELLYFIN-API] {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:841:14',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/node_modules/axios/dist/node/axios.cjs:841:14'
    },
    {
      TraceIndex: 2,
      line: '/app/node_modules/axios/dist/node/axios.cjs:3106:25'
    },
    { TraceIndex: 3, line: 'node:events:507:28' },
    {
      TraceIndex: 4,
      line: '/app/node_modules/follow-redirects/index.js:38:24'
    },
    { TraceIndex: 5, line: 'node:events:507:28' },
    { TraceIndex: 6, line: 'node:_http_client:104:11' },
    { TraceIndex: 7, line: 'node:_http_client:518:5' },
    { TraceIndex: 8, line: 'node:events:507:28' },
    { TraceIndex: 9, line: 'node:internal/streams/destroy:170:8' },
    { TraceIndex: 10, line: 'node:internal/streams/destroy:129:3' },
    {
      TraceIndex: 11,
      line: '/app/node_modules/axios/dist/node/axios.cjs:4224:41'
    },
    { TraceIndex: 12, line: 'node:internal/process/task_queues:105:5' },
    {
      TraceIndex: 13,
      line: '/app/backend/classes/jellyfin-api.js:549:24'
    },
    {
      TraceIndex: 14,
      line: 'at async /app/backend/routes/auth.js:112:24'
    }
  ],
  Message: 'connect ETIMEDOUT 192.168.178.225:8096',
  url: undefined
}
```

![Image](https://github.com/user-attachments/assets/a851efb8-aa94-4e65-9b52-9269e32883a8)

![Image](https://github.com/user-attachments/assets/b4db3b4f-a7b5-438d-ac99-aa470e9beffc)

### Compose.yml
```yml
services:
  jellystat-db:
    image: postgres:15.2
    shm_size: '1gb'
    container_name: jellystat-db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: MY_SECRET
      TZ: Europe/Berlin # timezone (ex: Europe/Paris)
    volumes:
      - jellystat-backup-data:/app/backend/backup-data
    ports:
      - "3030:3000"
    depends_on:
      - jellystat-db

networks:
  default:

volumes:
  postgres-data:
  jellystat-backup-data:
```
