### ISSUE TITLE
Jellystat DB Issue

### ISSUE THREAD

**Issue by gitdeath** [CyferShepard/Jellystat#54]
I'm running the docker image, which has been working for several weeks, but today I'm getting the below error.

`"Error: Unable to connect to Jellystat Backend"`

I went to investigate and the DB docker container is spamming the logs with this:

```
2023-06-16 22:18:24.889 UTC [200] DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.36.
2023-06-16 22:18:24.889 UTC [200] HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE jfstat REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
```

Not really sure what to do with it.

**Comment by NeuroDawg** [comment]
This happened to me after I rebooted my server. My jellstat containers didn't restart automatically, and I made the mistake of starting the jellystat container before I restarted the jellystat-db container. I recreated the jellyfin container and it worked without issues.

**Comment by FaNt4zMa** [comment]
Hey I'm experiencing the same issue whenever I reboot my PC. I tried changing the order in which the db and jellystat starts and made sure that "depends_on" was right but somehow Jellystat keeps booting before the db does..? Just as sanity check, I dont need PostgreSQL running in its own container do I? [Here's my docker-compose.yml](https://pastebin.com/WpZtbJmx) if you need.

**Comment by CyferShepard** [comment]
Hi @FaNt4zMa , Jellystat doesn't have a built-in postgres db, so you will need a container for it, this is due to people already having a postgres instance and wanting to integrate the db on that instance instead of spinning up a new one. Im currently trying to replicate this issue and checking how to mitigate it

**Comment by gitdeath** [comment]
I am running a clean postgress for just jellystat. Just copied the example template.

**Comment by FaNt4zMa** [comment]
Same here, but I did have to spin up a proper postgres container on first setup. Been running without it since then as I figured the docker-compose example had the postgres image running on its own, I didnt need another instance... I'm not advanced enough in Docker to know how to integrate jellystat db into postgres.

@CyferShepard It would be nice if it did have built-in db as most Windows native apps like Sonarr, Radarr, etc have built-in db. Maybe having the choice between built-in and external db would be the best?

**Comment by CyferShepard** [comment]
Il look into doing this instead, initially I did plan to take this approach but after some discussion with a few friends we settled on having it separate.

**Comment by gitdeath** [comment]
Restarting the Jellystat container and leaving the Jellystat_db alone does 'fix' the issue in my use case. 

Docker config

```
  jellystat-db:
    image: postgres
    environment:
      POSTGRES_USER: ###########
      POSTGRES_PASSWORD: #########
    volumes:
    - jellystat_db:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: ##########
      POSTGRES_PASSWORD: #############
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ################
    ports:
      - "3000:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - jellystat:/app/backend/backup-data # Mounting the volume
    depends_on:
      - jellystat-db
```
