### ISSUE TITLE
Setup JellyStat with Docker

### ISSUE THREAD

**Issue by xtrandom** [CyferShepard/Jellystat#62]
Hi all,

I have my setup running with caddy and gluten-vpn. In portainer, I have a stack with the following setup:

```
services:
  gluetun:
    image: qmcgaw/gluetun:v3.33.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 9696:9696     # prowlarr
      ...
    volumes:
      ...
    environment:
      ...
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.9
    container_name: jellyfin
    network_mode: "host"
    environment:
      ...
    volumes:
      ...
    ports:
      ...
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.4.1.3258-ls16
    container_name: prowlarr
    network_mode: "service:gluetun"
    depends_on:
      "gluetun":
        condition: service_healthy
    environment:
      ...
    volumes:
      ...
#    ports: # specified under gluten above
#      - 9696:9696
    restart: unless-stopped

  ...
```

Now I am trying to add jellystat into the stack like so:
```
  jellystat-db:
    image: postgres
    container_name: jellystat-db
    network_mode: "host"
    environment:
      POSTGRES_USER: [redacted]
      POSTGRES_PASSWORD: [redacted]
    volumes:
      - /root/docker/postgres/data:/var/lib/postgresql/data # Mounting the volume
    restart: unless-stopped
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    network_mode: "host"
    depends_on:
      - jellystat-db
    environment:
      POSTGRES_USER: [redacted]
      POSTGRES_PASSWORD: [redacted]
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'secret-string'
    ports:
      - "9797:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - /root/docker/jellystat/backup-data:/app/backend/backup-data # Mounting the volume
    restart: unless-stopped
```

Both of the containers are in 'running' state. I see the following in the logs:
```
# jellystat-db
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-07-17 02:15:33.832 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
[1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[1] LOG:  listening on IPv6 address "::", port 5432
[1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[29] LOG:  database system was shut down at 2023-07-17 02:15:32 UTC
[1] LOG:  database system is ready to accept connections
[27] LOG:  checkpoint starting: time
[27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.010 s, total=0.069 s; sync files=2, longest=0.006 s, average=0.005 s; distance=0 kB, estimate=0 kB

# jellystat
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

The setup is similar to other containers, so what am I doing wrong?  I've checked the formatting of the stack file and it seems to be correct. Any help would be appreciated!

Thank you

**Comment by CyferShepard** [comment]
Hi @xtrandom , this looks like the db didn't initialise properly. Either it crashed or was stopped while postgres setup the environment. Go to the folder  where you mapped the postgres data to. Empty out that folder and start the postgres container again to redo the initialisation. This is because if postgres sees files in that folder it won't attempt to recreate a db if you recreate the container

**Comment by CyferShepard** [comment]
Are you running on an arm platform by any chance?

**Comment by ac-ih** [comment]
Coincidentally, I was just coming to add this potentially critical information: I'm running this on Raspberry Pi 4.

Apologies for forgetting to mention it sooner.

**Comment by xtrandom** [comment]
First, thank you for the reply!

I deleted everything with /root/docker/postgres/ and /root/docker/jellystat/, deleted the containers, and updated the stack. I saw the same output (for jellystat-db) / error (for jellystat) in both container's logs.

 I'm running this on Raspberry Pi 4, Model B. Apologies for forgetting to mention it sooner.

**Comment by CyferShepard** [comment]
Ah, that makes sense, it's currently not supported on the arm platform yet, I was meant to develop for that platform but the the raspberry Pi I had on hand was broken so I don't have the hardware to test at the moment. Let me try and do a build and Il add an experimental version

**Comment by xtrandom** [comment]
> Let me try and do a build and Il add an experimental version

That'll be most appreciated! Would really like to get this project to my setup.

**Comment by CyferShepard** [comment]
can you try with the `arm` tag

**Comment by xtrandom** [comment]
Same error. Does it matter that the `arm` tag still shows OS/ARCH as `linux/amd64` (same as `latest` tag)? If I check the details for prowlarr, it shows `linux/arm64` too.

cyfershepard/jellystat:
![image](https://github.com/CyferShepard/Jellystat/assets/68791912/16afadfc-c698-44c0-82c2-bae0481c3337)

linuxserver/prowlarr:
![image](https://github.com/CyferShepard/Jellystat/assets/68791912/09f7fae0-2bb7-4ce0-b884-f3956a7f3bae)

**Comment by xtrandom** [comment]
Thank you so much for the quick turnaround!

Used the latest build (which now shows OS/ARCH as `linux/arm/v7`) and now seeing the following error in jellystat logs:
```
npm ERR! Invalid version: "1.0.5.0"
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-19T17_07_57_461Z-debug.log
```

**Comment by xtrandom** [comment]
No change with the latest build. Do you know how I can access that file? I don't see `.npm` folder within /root directory in rPi.

I moved the config to a fresh stack to get it up and running at least, so you should be able to replicate the error. 

```
version: '3'
services:
  jellystat-db:
    image: postgres
    container_name: jellystat-db
    # network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /root/docker/postgres/data:/var/lib/postgresql/data # Mounting the volume
    restart: unless-stopped

  jellystat:
    image: cyfershepard/jellystat:arm
    container_name: jellystat
    # network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'secret-string'
    ports:
      - "9797:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - /root/docker/jellystat/backup-data:/app/backend/backup-data # Mounting the volume
    restart: unless-stopped

    depends_on:
      - jellystat-db
networks:
  default:
```
